- name: Install packages
  ansible.builtin.apt:
    state: present
    update_cache: true
    install_recommends: false
    pkg:
      - unattended-upgrades
      - powermgmt-base
      - python3-gi
  tags:
    - unattended_upgrades

- name: Template a file to /etc/apt/apt.conf.d/20auto-upgrades
  ansible.builtin.copy:
    content: |
      APT::Periodic::Update-Package-Lists "{{ unattended_upgrades_enable | ternary('1', '0') }}";
      APT::Periodic::Unattended-Upgrade "{{ unattended_upgrades_enable | ternary('1', '0') }}";
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: "0644"
  notify: Restart unattended-upgrades service
  tags:
    - unattended_upgrades

- name: Template a file to /etc/apt/apt.conf.d/58unattended-upgrades_origins
  ansible.builtin.copy:
    content: |
      Unattended-Upgrade::Origins-Pattern {
          "{{ unattended_upgrades_Origins-Pattern }}"
      };
    dest: /etc/apt/apt.conf.d/58unattended-upgrades_origins
    owner: root
    group: root
    mode: "0644"
  notify: Restart unattended-upgrades service
  tags:
    - unattended_upgrades
  when: unattended_upgrades_Origins-Pattern is defined

- name: Template a file to /etc/apt/apt.conf.d/59unattended-upgrades_settings
  ansible.builtin.copy:
    content: |
      Unattended-Upgrade::AutoFixInterruptedDpkg "{{ unattended_upgrades_autofixinterrupteddpkg }}";
      Unattended-Upgrade::MinimalSteps "{{ unattended_upgrades_minimalsteps }}";
      Unattended-Upgrade::InstallOnShutdown "{{ unattended_upgrades_installonshutdown }}";
      Unattended-Upgrade::Mail "{{ unattended_upgrades_mail }}";
      Unattended-Upgrade::MailReport "{{ unattended_upgrades_mailreport }}";
      Unattended-Upgrade::Remove-Unused-Dependencies "{{ unattended_upgrades_remove_unused_dependencies }}";
      Unattended-Upgrade::Automatic-Reboot "{{ unattended_upgrades_automatic_reboot }}";
      Unattended-Upgrade::Automatic-Reboot-WithUsers "{{ unattended_upgrades_automatic_reboot_withusers }}";
      Unattended-Upgrade::Automatic-Reboot-Time "{{ unattended_upgrades_automatic_reboot_time }}";
    dest: /etc/apt/apt.conf.d/59unattended-upgrades_settings
    owner: root
    group: root
    mode: "0644"
  notify: Restart unattended-upgrades service
  tags:
    - unattended_upgrades

- name: Template a file to /etc/systemd/system/apt-daily.timer
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Daily apt download activities

      [Timer]
      OnCalendar={{ unattended_upgrades_update_calendar }}
      RandomizedDelaySec={{ unattended_upgrades_update_delay }}
      Persistent=true

      [Install]
      WantedBy=timers.target
    dest: /etc/systemd/system/apt-daily.timer
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd
  tags:
    - unattended_upgrades
  when: unattended_upgrades_update_calendar is defined

- name: Template a file to /etc/systemd/system/apt-daily-upgrade.timer
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Daily apt upgrade and clean activities
      After=apt-daily.timer

      [Timer]
      OnCalendar={{ unattended_upgrades_upgrade_calendar }}
      RandomizedDelaySec={{ unattended_upgrades_upgrade_delay }}
      Persistent=true

      [Install]
      WantedBy=timers.target
    dest: /etc/systemd/system/apt-daily-upgrade.timer
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd
  tags:
    - unattended_upgrades
  when: unattended_upgrades_upgrade_calendar is defined
